matrix:
  include:
    - stage: test
      name: test_linux_3_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install xmltodict matplotlib numpy scipy pandas cython gcc_linux-64
        - git config --global user.email "${GH_EMAIL}"
        - git config --global user.name "${GH_USER}"
        - git clone https://${GH_USER}:${GH_TOKEN}@github.com/pyiron/pyiron-resources.git
        - mv 'data/atomman.lammps.Potential models/NIST IPR' NISTiprpy
        - pip install atomman 
      script:
        - python .ci_support/potential.py
      deploy:
        - provider: script
          script: 
            - bash .ci_support/deploy.sh "${TRAVIS_COMMIT_MESSAGE}"
          on:
            branch: master
